src/VZ/CalendarBundle/Entity/Event.php
<?php
namespace VZ\CalendarBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="VZ\CalendarBundle\Repository\EventRepository")
 * @ORM\Table(name="event")
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="date")
     */
    public $startDate;

    /**
     * @ORM\Column(type="time")
     */
    public $startTime;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    public $endDate;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    public $endTime;

    /**
     * @ORM\Column(type="date")
     */
    public $cutoffDate;

    /**
     * @ORM\Column(type="time")
     */
    public $cutoffTime;

    /**
     *
     * @ORM\Column(type="string", length=512)
     */
    protected $summary;

    /**
     *
     * @ORM\Column(type="string", length=32768, nullable=true)
     */
    protected $details;

    /**
     *
     * @ORM\Column(type="integer")
     */
    protected $totalSlots;

    /**
     *
     * @ORM\Column(type="integer")
     */
    protected $usedSlots;

    /**
     *
     * @ORM\Column(type="integer")
     */
    protected $quota;

    /**
     *
     * @ORM\Column(type="integer")
     */
    protected $priceMember;

    /**
     *
     * @ORM\Column(type="integer")
     */
    protected $priceNonMember;

    /**
     * @ORM\Column(type="datetime")
     */
    public $quotaNotifyDate;

    /**
     * Flag set when the quota email has been sent
     *
     * @ORM\Column(type="boolean", nullable=true)
     */
    public $quotaNotified;

    /**
     * @ORM\OneToMany(targetEntity="EventUser", mappedBy="event", cascade={"persist"}, orphanRemoval=true)
     * @var type
     */
    private $attendees;

    /**
     * @ORM\OneToMany(targetEntity="EventLog", mappedBy="event")
     * @var type
     */
    private $logs;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set startDate
     *
     * @param date $startDate
     * @return Event
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;
        return $this;
    }

    /**
     * Get startDate
     *
     * @return date 
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * Set startTime
     *
     * @param time $startTime
     * @return Event
     */
    public function setStartTime($startTime)
    {
        $this->startTime = $startTime;
        return $this;
    }

    /**
     * Get startTime
     *
     * @return time 
     */
    public function getStartTime()
    {
        return $this->startTime;
    }

    /**
     * Set endDate
     *
     * @param date $endDate
     * @return Event
     */
    public function setEndDate($endDate)
    {
        $this->endDate = $endDate;
        return $this;
    }

    /**
     * Get endDate
     *
     * @return date 
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * Set endTime
     *
     * @param time $endTime
     * @return Event
     */
    public function setEndTime($endTime)
    {
        $this->endTime = $endTime;
        return $this;
    }

    /**
     * Get endTime
     *
     * @return time 
     */
    public function getEndTime()
    {
        return $this->endTime;
    }

    /**
     * Set summary
     *
     * @param string $summary
     * @return Event
     */
    public function setSummary($summary)
    {
        $this->summary = $summary;
        return $this;
    }

    /**
     * Get summary
     *
     * @return string 
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Set details
     *
     * @param string $details
     * @return Event
     */
    public function setDetails($details)
    {
        $this->details = $details;
        return $this;
    }

    /**
     * Get details
     *
     * @return string 
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Set totalSlots
     *
     * @param integer $totalSlots
     * @return Event
     */
    public function setTotalSlots($totalSlots)
    {
        $this->totalSlots = $totalSlots;
        return $this;
    }

    /**
     * Get totalSlots
     *
     * @return integer 
     */
    public function getTotalSlots()
    {
        return $this->totalSlots;
    }

    /**
     * Set usedSlots
     *
     * @param integer $usedSlots
     * @return Event
     */
    public function setUsedSlots($usedSlots)
    {
        $this->usedSlots = $usedSlots;
        return $this;
    }

    /**
     * Get usedSlots
     *
     * @return integer 
     */
    public function getUsedSlots()
    {
        return $this->usedSlots;
    }

    /**
     * Set quota
     *
     * @param integer $quota
     * @return Event
     */
    public function setQuota($quota)
    {
        $this->quota = $quota;
        return $this;
    }

    /**
     * Get quota
     *
     * @return integer 
     */
    public function getQuota()
    {
        return $this->quota;
    }

    /**
     * Set priceMember
     *
     * @param integer $priceMember
     * @return Event
     */
    public function setPriceMember($priceMember)
    {
        $this->priceMember = $priceMember;
        return $this;
    }

    /**
     * Get priceMember
     *
     * @return integer 
     */
    public function getPriceMember()
    {
        return $this->priceMember;
    }

    /**
     * Set priceNonMember
     *
     * @param integer $priceNonMember
     * @return Event
     */
    public function setPriceNonMember($priceNonMember)
    {
        $this->priceNonMember = $priceNonMember;
        return $this;
    }

    /**
     * Get priceNonMember
     *
     * @return integer 
     */
    public function getPriceNonMember()
    {
        return $this->priceNonMember;
    }

    /**
     * Set quotaNotifyDate
     *
     * @param datetime $quotaNotifyDate
     * @return Event
     */
    public function setQuotaNotifyDate($quotaNotifyDate)
    {
        $this->quotaNotifyDate = $quotaNotifyDate;
        return $this;
    }

    /**
     * Get quotaNotifyDate
     *
     * @return datetime 
     */
    public function getQuotaNotifyDate()
    {
        return $this->quotaNotifyDate;
    }
    public function __construct()
    {
        $this->attendees = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Add attendees
     *
     * @param VZ\CalendarBundle\Entity\EventUser $attendees
     * @return Event
     */
    public function addEventUser(\VZ\CalendarBundle\Entity\EventUser $attendees)
    {
        if ($this->totalSlots - $this->usedSlots - $attendees->getReservedSlots() < 0) {
            return false;
        }
        $this->attendees[] = $attendees;
        $this->usedSlots  += $attendees->getReservedSlots();
        return $this;
    }

    /**
     * Get attendees
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getAttendees()
    {
        return $this->attendees;
    }

    /**
     * Check if given user is attending this event
     *
     * @param User $user user object from logged in or other user (NOT EventUser Object)
     * @return true if the given user is attending, false if not
     */
    public function checkAttendee($user)
    {
        // run through linked records and check if any match given user
        foreach ($this->attendees as $attendee) {
            if ($attendee->getUser()->getId() == $user->getId()) {
                return true;
            }
        }
        return false;
    }

    /**
     * Remove an attendee from this event
     *
     * @param User $user user object from logged in or other user (NOT EventUser Object)
     * @return bool true if the user was found and removed, else false
     */
    public function removeAttendee($user)
    {
        foreach ($this->attendees as $attendee) {
            if ($attendee->getUser()->getId() == $user->getId()) {
                $usedSlots = $this->usedSlots - $attendee->getReservedSlots();
                $this->setUsedSlots($usedSlots);

                $this->attendees->removeElement($attendee);
                return true;
            }
        }
        return false;
    }

    /**
     * Work out how many slots are available and return the amount
     *
     * @return int number of slots open
     */
    public function getOpenSlots()
    {
        return $this->totalSlots - $this->usedSlots;
    }

    /**
     * Set cutoffDate
     *
     * @param date $cutoffDate
     * @return Event
     */
    public function setCutoffDate($cutoffDate)
    {
        $this->cutoffDate = $cutoffDate;
        return $this;
    }

    /**
     * Get cutoffDate
     *
     * @return date 
     */
    public function getCutoffDate()
    {
        return $this->cutoffDate;
    }

    /**
     * Set cutoffTime
     *
     * @param time $cutoffTime
     * @return Event
     */
    public function setCutoffTime($cutoffTime)
    {
        $this->cutoffTime = $cutoffTime;
        return $this;
    }

    /**
     * Get cutoffTime
     *
     * @return time 
     */
    public function getCutoffTime()
    {
        return $this->cutoffTime;
    }

    /**
     * Add attendees
     *
     * @param VZ\CalendarBundle\Entity\EventUser $attendees
     * @return Event
     */
    public function addAttendee(\VZ\CalendarBundle\Entity\EventUser $attendees)
    {
        $this->attendees[] = $attendees;
        return $this;
    }

    /**
     * Set quotaNotified
     *
     * @param boolean $quotaNotified
     * @return Event
     */
    public function setQuotaNotified($quotaNotified)
    {
        $this->quotaNotified = $quotaNotified;
        return $this;
    }

    /**

src/VZ/CalendarBundle/Form/EventType.php
<?php

namespace VZ\CalendarBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class EventType extends AbstractType
{
    /**
     * Builds the form for an Event (for adding or editing an event)
     *
     * @param \Symfony\Component\Form\FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('summary')
            ->add(
                'details',
                'textarea',
                array(
                    'required' => false,
                    'label' => 'event_form_details',
                    'attr' => array('class' => 'abc')
                )
            )
            ->add(
                'startDate', 'date', array(
                    'widget' => 'single_text',
                    'format' => 'dd.MM.yyyy',
                    'attr' => array('class' => 'date')
                )
            )
            ->add('startTime', 'time', array(
                    'widget' => 'single_text',
                    'attr' => array('class' => 'time')
                )
            )
            ->add('cutoffDate', 'date', array(
                    'widget' => 'single_text',
                    'format' => 'dd.MM.yyyy',
                    'attr' => array('class' => 'date')
                )
            )
            ->add('cutoffTime', 'time', array(
                    'widget' => 'single_text',
                    'attr' => array('class' => 'time')
                )
            )
            ->add('totalSlots')
            ->add('quota')
            ->add('quotaNotifyDate', 'date', array(
                    'widget' => 'single_text',
                    'format' => 'dd.MM.yyyy',
                    'attr' => array('class' => 'date')
                )
            )
            ->add('priceMember', 'integer')
            ->add('priceNonMember', 'integer')
        ;
    }
    public function getName()
    {
        return 'event';
    }
}

src/VZ/CalendarBundle/Resources/views/Event/_eventform.html.twig
{{ form_widget(form) }}

src/VZ/CalendarBundle/Resources/views/Event/addAttendee.html.twig
{% extends "VZCalendarBundle::layout.html.twig" %}

{% block content %}

<h1>{{ "event_joining" | trans({'%name%': event.summary }) }}</h1>

<form action="{{ path('vz_calendar_event_addattendee', { 'id': event.id }) }}" method="post" {{ form_enctype(form) }}>
    {% include "VZCalendarBundle:EventUser:_eventuserform.html.twig" with {'form': form } %}

    <button type="submit" class="btn btn-primary">{{ "submit" | trans }}</button>
</form>

{% endblock %}

src/VZ/CalendarBundle/Resources/views/Event/busview.html.twig
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Calendar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block stylesheets %}
    {% stylesheets
                '%kernel.root_dir%/../vendor/twitter/bootstrap/docs/assets/css/bootstrap.css'
                '%kernel.root_dir%/../vendor/twitter/bootstrap/docs/assets/css/bootstrap-responsive.css'
                '@VZCalendarBundle/Resources/public/css/calendar.css'
                output='assetic/*.css'
            %}
    <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
    {% endblock %}
</head>
<body>

<h1>{{ "event_title" | trans({'%title%': event.summary, '%date%': event.startDate|date('d.m.Y')}) }}</h1>
<h2>{{ 'meeting_at' | trans({'%time%': event.startTime|date('H:i') }) }}</h2>
<p>{{ event.details }}</p>
<p>
    {{ 'available_slots' | transchoice(event.openSlots) }}.
    {{ 'event_totalslots' | trans }} {{ event.usedSlots }} / {{ event.totalSlots }}
</p>
<table class="table table-striped table-bordered">
    <caption>
        {{ 'attendee_list' | trans }}
    </caption>
    <thead>
        <tr>
            <th>{{ 'name' | trans }}</th>
            <th>{{ 'is_member' | trans }}</th>
            <th>{{ 'reserved_slots' | trans }}</th>
            <th>{{ 'payment_method' | trans }}</th>
            <th>{{ 'amount_paid' | trans }}</th>
            <th>{# blank #}</th>
        </tr>
    </thead>
    <tbody>
    {% for user in event.attendees %}
        <tr>
            <td>{{ user.user }}</td>

            <td>{{ user.user.isMember ? 'yes'|trans : 'no'|trans }}</td>
            <td>{{ user.reservedSlots }}</td>
            <td>{{ user.paymentMethod }}</td>
            <td>[      ]</td>
            <td>[      ]</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
{% endblock %}

src/VZ/CalendarBundle/Resources/views/Event/edit.html.twig
{% extends "VZCalendarBundle::layout.html.twig" %}

{% block content %}

<h2>{{ "event_edit" | trans }}</h2>
<form action="{{ path('vz_calendar_event_update', { 'id': event.id }) }}" method="post" {{ form_enctype(form) }}>
    {% include "VZCalendarBundle:Event:_eventform.html.twig" with {'form': form } %}

    <button type="submit" class="btn btn-primary">{{ "submit" | trans }}</button>
    <a class="btn" href="{{ path("vz_calendar_event_index") }}">
        {{ "back_to_list" | trans }}
    </a>

    <a class="btn btn-danger" href="{{ path("vz_calendar_event_delete", { 'id': event.id }) }}">
        {{ "event_delete" | trans }}
    </a>
</form>

{% endblock %} 

src/VZ/CalendarBundle/Resources/views/Event/index.html.twig
{% extends "VZCalendarBundle::layout.html.twig" %}

{% block content %}

{% if events|length > 0 %}
<h1>{{ 'up_and_coming_events' | trans }}</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>{{ "event_summary" | trans }}</th>
            <th>{{ "event_start" | trans }}</th>
            <th>{{ "event_totalslots" | trans }}</th>
            <th>{{ "free_slots" | trans }}</th>
            <th>{{ "event_actions" | trans }}</th>
        </tr>
    </thead>
    <tbody>
    {% for event in events %}
        <tr>
            <td>{{ event.summary }}</td>
            <td>{{ event.startDate|date('d.m.Y') }} {{ event.startTime|date('H:i') }}</td>
            <td>{{ event.totalSlots }}</td>
            <td>{{ event.openSlots }}</td>
            <td>
                <a class="btn btn-success" href="{{ path("vz_calendar_event_view", { 'id': event.id }) }}">
                    {{ "event_view" | trans }}
                </a>
                <a class="btn btn-info" href="{{ path("vz_calendar_event_busview", { 'id': event.id }) }}">
                    {{ "event_busprintout" | trans }}
                </a>
                <a class="btn btn-primary" href="{{ path("vz_calendar_event_edit", { 'id': event.id }) }}">
                    {{ "event_edit" | trans }}
                </a>
                <a class="btn" href="{{ path("vz_calendar_event_addattendee", { 'id': event.id }) }}">
                    {{ "event_adduser" | trans }}
                </a>
                <a class="btn btn-danger" href="{{ path("vz_calendar_event_delete", { 'id': event.id }) }}">
                    {{ "event_delete" | trans }}
                </a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h1>{{ "no_events_found" | trans }}</h1>
{% endif %}

<a class="btn" href="{{ path("vz_calendar_event_create") }}">{{ "event_create_new" | trans }}</a>

{% endblock %} 

src/VZ/CalendarBundle/Resources/views/Event/new.html.twig
{% extends "VZCalendarBundle::layout.html.twig" %}

{% block content %}

<h2>{{ "event_new" | trans }}</h2>

<form action="{{ path('vz_calendar_event_new') }}" method="post" {{ form_enctype(form) }}>
    {% include "VZCalendarBundle:Event:_eventform.html.twig" with {'form': form } %}

    <button type="submit" class="btn btn-primary">{{ "submit" | trans }}</button>
    <a class="btn" href="{{ path("vz_calendar_event_index") }}">
        {{ "back_to_list" | trans }}
    </a>
</form>

{% endblock %} 

src/VZ/CalendarBundle/Resources/views/Event/view.html.twig
{% extends "VZCalendarBundle::layout.html.twig" %}

{% block content %}

<div class="hero-unit">
    <a class="btn btn-info" href="{{ path("vz_calendar_event_busview", { 'id': event.id }) }}">
        {{ "event_busprintout" | trans }}
    </a>
    <h1>{{ "event_title" | trans({'%title%': event.summary, '%date%': event.startDate|date('d.m.Y')}) }}</h1>
    <h2>{{ 'meeting_at' | trans({'%time%': event.startTime|date('H:i') }) }}</h2>
    <p>{{ event.details }}</p>
    <p>
        {{ 'available_slots' | transchoice(event.openSlots) }}
    </p>
    <h3>{{ 'attendee_list' | trans }}</h3>
        {% for user in event.attendees %}
        <p>
            {{ user.user }}
            <a href="{{ path("vz_calendar_event_deleteuser", { 'id': event.id, 'userId': user.user.id } )}}"
               class="btn btn-danger">{{ 'user_remove_from_event' | trans }} </a>
        </p>
        {% endfor %}
    <h3>{{ 'email_list' | trans }}</h3>
    <p>{{ 'email_list_copy_paste' | trans }}</p>
    <code>
        {{ event.getAttendeeEmails|join(', ') }}
    </code>
    <h3>{{ 'log' | trans }}</h3>
        {% for log in event.logs %}
        <p>
            {{ log.logDate | date('d.m.Y H:i') }} {{ log.user }} {{ log.action }} {{ log.detail }}
        </p>
        {% endfor %}
</div>

{% endblock %}